# Generated by Django 5.0.4 on 2024-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(help_text='Укажите страну, где был произведен фильм', max_length=100, verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата, когда запись была создана. Устанавливается автоматически.', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(help_text='Введите жанр фильма, например: драма, комедия, экшн', max_length=100, verbose_name='Жанр фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.URLField(help_text='Введите URL-адрес изображения или постера фильма', verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Введите название фильма, до 250 символов', max_length=250, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(help_text='Введите полный URL-адрес с информацией о фильме', verbose_name='Ссылка на информацию о фильме'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(help_text='Введите год, когда фильм был выпущен', verbose_name='Год выпуска'),
        ),
    ]
